version: 0.0.{build}
image: Visual Studio 2019

configuration: Release

init:
- ps: $env:nuget_ver=$env:appveyor_build_version
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '1.0.{build}'
  assembly_version: '1.0.{build}'
  file_version: '1.0.{build}'
  informational_version: '{version}'
  
matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore src\DotJEM.AspNetCore.FluentRouting.sln
  - cmd: nuget restore src\DotJEM.AspNetCore.FluentRouting.sln

build:
  project: src\DotJEM.AspNetCore.FluentRouting.sln
  publish_nuget: true
  publish_nuget_symbols: true

  
deploy:
  provider: NuGet
  api_key:
    secure: KEHWtW02rf5aCAlwchP0Siow5EA24hwtm09uvsR58bMWirJ8uXl1SidBnNCfJ3cw
  skip_symbols: true
  on:
    branch: master 